import = [
	"~/.config/alacritty/themes/themes/hardhacker.toml"
]
[font]
builtin_box_drawing = true
size = 17.0
[font.normal]
family = "JetBrainsMono"
style = "Regular"
[font.bold]
family = "JetBrainsMono"
style = "Bold"
[font.italic]
family = "JetBrainsMono"
style = "Italic"
