#! /bin/sh

picom -f &
flameshot &
sh $HOME/.config/.scripts/random_wallpaper & 

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config presel_feedback_color "#838159"

bspc config focus_follows_pointer true
bspc config pointer_modifier    super

bspc rule -a firefox desktop='^3'

sh $HOME/.config/polybar/launch.sh 
